const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

// TAPROFILE may be deleted?
const TAPROFILE = {
    FETCH: 'TAPROFILE_FETCH',
    FETCH_ERROR: 'TAPROFILE_FETCH_ERROR',
    FETCH_SUCCESS: 'TAPROFILE_FETCH_SUCCESS',
}

const ACCOUNT_INFO = {
    FETCH: 'ACCOUNT_INFO_FETCH',
    FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS'
};

export { ACCOUNT, TAPROFILE, ACCOUNT_INFO };